export type ToolCategory = 'Organize' | 'Optimize' | 'Convert' | 'Edit' | 'Security';
export type ToolType = 'easy' | 'heavy' | 'ocr';

export interface ToolOption {
  key: string;
  label: string;
  type: 'select' | 'text' | 'number' | 'range';
  options?: string[];
  defaultValue?: string | number;
  min?: number;
  max?: number;
  placeholder?: string;
}

export interface ToolConfig {
  slug: string;
  label: string;
  tagline: string;
  description: string;
  category: ToolCategory;
  type: ToolType;
  icon: string;
  ninjaWeapon: string;
  ninjaImage: string;
  apiPath: string;
  acceptedTypes: string[];
  acceptedLabel: string;
  multiFile: boolean;
  options?: ToolOption[];
  outputExt: string;
  tips: string[];
  relatedSlugs: string[];
}

export const TOOLS: Record<string, ToolConfig> = {
  merge: {
    slug: 'merge',
    label: 'Merge PDF',
    tagline: 'Unite your scrolls into one',
    description: 'Combine multiple PDFs in the exact order you want. Drag to reorder, then strike — the result is a single, perfectly fused document.',
    category: 'Organize',
    type: 'easy',
    icon: '⊕',
    ninjaWeapon: 'Dual Katana',
    ninjaImage: '/ninja_merge.png',
    apiPath: '/v1/tools/merge',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload files in the order you want them merged', 'You can upload up to 20 PDFs at once', 'Files are deleted from our servers after 1 hour'],
    relatedSlugs: ['split', 'organize', 'compress'],
  },
  split: {
    slug: 'split',
    label: 'Split PDF',
    tagline: 'Slice with surgical precision',
    description: 'Cut your PDF into individual pages or custom ranges. Extract exactly what you need — like a throwing star hitting its mark.',
    category: 'Organize',
    type: 'easy',
    icon: '⊗',
    ninjaWeapon: 'Kunai',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/split',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'mode', label: 'Split Mode', type: 'select', options: ['all', 'range'], defaultValue: 'all' },
    ],
    outputExt: 'zip',
    tips: ['Choose "All Pages" to extract every page as a separate PDF', 'Use "Range" to extract specific page sets like 1-3, 5-7', 'Range format: use comma-separated ranges'],
    relatedSlugs: ['merge', 'organize', 'crop'],
  },
  organize: {
    slug: 'organize',
    label: 'Organize PDF',
    tagline: 'Master the order of your scrolls',
    description: 'Reorder, delete or arrange PDF pages with precision. Total control — like a ninja choreographing a perfect battle.',
    category: 'Organize',
    type: 'easy',
    icon: '⊞',
    ninjaWeapon: 'Nunchaku',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/organize',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Enter page numbers in the new order (e.g. 3,1,2,5)', 'Skip a page number to delete it', 'Use this after merging to perfect the sequence'],
    relatedSlugs: ['merge', 'split', 'rotate'],
  },
  compress: {
    slug: 'compress',
    label: 'Compress PDF',
    tagline: 'Reduce size, keep the power',
    description: 'Shrink your PDF file size by up to 70% while keeping visual quality intact. Swift, efficient — a ninja never carries excess weight.',
    category: 'Optimize',
    type: 'easy',
    icon: '↘',
    ninjaWeapon: 'Iron Fan',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/compress',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'quality', label: 'Compression Level', type: 'select', options: ['screen', 'ebook', 'printer', 'prepress'], defaultValue: 'ebook' },
    ],
    outputExt: 'pdf',
    tips: ['"Ebook" quality is recommended — great balance of size and clarity', '"Screen" gives the smallest file, best for emails', '"Prepress" keeps highest quality for printing'],
    relatedSlugs: ['repair', 'pdf-to-pdfa', 'merge'],
  },
  repair: {
    slug: 'repair',
    label: 'Repair PDF',
    tagline: 'Restore what is broken',
    description: 'Recover data from damaged or corrupt PDF files. Even a fallen warrior can be revived — our repair tool finds and fixes structural errors.',
    category: 'Optimize',
    type: 'easy',
    icon: '⚙',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/repair',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Works on most structurally damaged PDFs', 'Cannot recover password-protected encrypted files', 'Try compress after repair to reduce any bloat'],
    relatedSlugs: ['compress', 'pdf-to-pdfa', 'unlock'],
  },
  'pdf-to-pdfa': {
    slug: 'pdf-to-pdfa',
    label: 'PDF to PDF/A',
    tagline: 'Archival-grade preservation',
    description: 'Convert your PDF to the ISO-standardized PDF/A format for long-term archiving. Your document will remain readable for generations to come.',
    category: 'Optimize',
    type: 'heavy',
    icon: '◈',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/jobs/pdf-to-pdfa',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['PDF/A is the standard for legal and government archiving', 'All fonts and colors are embedded for future compatibility', 'Larger file size is expected — this is by design'],
    relatedSlugs: ['compress', 'repair', 'protect'],
  },
  'pdf-to-word': {
    slug: 'pdf-to-word',
    label: 'PDF to Word',
    tagline: 'Unlock the content within',
    description: 'Transform any PDF into a fully editable DOC/DOCX file with ~85% layout fidelity. Extract text, tables, and formatting in seconds.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Tanto',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-word',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'docx',
    tips: ['Best results on text-based PDFs (not scanned images)', 'Run OCR first if your PDF is a scanned document', 'Complex layouts may need minor manual cleanup'],
    relatedSlugs: ['word-to-pdf', 'pdf-to-excel', 'ocr'],
  },
  'word-to-pdf': {
    slug: 'word-to-pdf',
    label: 'Word to PDF',
    tagline: 'Strike without mercy',
    description: 'Convert DOC and DOCX files to pixel-perfect PDFs using LibreOffice rendering. Preserve every font, table and image — no quality lost.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/word-to-pdf',
    acceptedTypes: ['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    acceptedLabel: 'DOC or DOCX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['All fonts and images are embedded in the output', 'Works with both .doc (old) and .docx (new) format', 'Processing typically takes 10-30 seconds'],
    relatedSlugs: ['pdf-to-word', 'compress', 'protect'],
  },
  'pdf-to-ppt': {
    slug: 'pdf-to-ppt',
    label: 'PDF to PowerPoint',
    tagline: 'Transform presentations instantly',
    description: 'Convert your PDF into PPT/PPTX slides. Each page becomes a visual slide — perfect for presentations that started as PDFs.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Kama',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-ppt',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pptx',
    tips: ['Each PDF page becomes one presentation slide', 'Slides are image-based — text will not be editable', 'Perfect for PDFs with visual content and charts'],
    relatedSlugs: ['ppt-to-pdf', 'pdf-to-word', 'pdf-to-jpg'],
  },
  'ppt-to-pdf': {
    slug: 'ppt-to-pdf',
    label: 'PowerPoint to PDF',
    tagline: 'Seal your slides in PDF armor',
    description: 'Convert PPT and PPTX presentations to universally viewable PDFs. Protect your design — share without fear of font or layout shifts.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/ppt-to-pdf',
    acceptedTypes: ['application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    acceptedLabel: 'PPT or PPTX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Animations and transitions will not be preserved', 'All embedded images and fonts are captured', 'Processing takes 15-45 seconds depending on file size'],
    relatedSlugs: ['pdf-to-ppt', 'compress', 'word-to-pdf'],
  },
  'pdf-to-excel': {
    slug: 'pdf-to-excel',
    label: 'PDF to Excel',
    tagline: 'Extract data like extracting secrets',
    description: 'Pull tables and data from PDFs directly into Excel spreadsheets. A ninja always knows how to retrieve what is hidden.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Tekko',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-excel',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'xlsx',
    tips: ['Best results on PDFs with clear table borders', 'Free-form layouts may require manual cleanup', 'Run OCR first on scanned PDFs before converting'],
    relatedSlugs: ['excel-to-pdf', 'pdf-to-word', 'ocr'],
  },
  'excel-to-pdf': {
    slug: 'excel-to-pdf',
    label: 'Excel to PDF',
    tagline: 'Forge spreadsheets into PDFs',
    description: 'Transform XLSX and XLS spreadsheets into clean, shareable PDFs. Every cell, formula result, and chart — preserved in PDF armor.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Naginata',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/excel-to-pdf',
    acceptedTypes: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    acceptedLabel: 'XLS or XLSX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Each worksheet becomes a separate PDF page', 'Print area settings are respected', 'Freeze panes and row/column headers are captured'],
    relatedSlugs: ['pdf-to-excel', 'compress', 'word-to-pdf'],
  },
  'pdf-to-jpg': {
    slug: 'pdf-to-jpg',
    label: 'PDF to JPG',
    tagline: 'See every page as an image',
    description: 'Convert each PDF page into a high-resolution JPG image. Extract charts, diagrams, or visuals — or create a full image archive.',
    category: 'Convert',
    type: 'easy',
    icon: '⊡',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/pdf-to-jpg',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'dpi', label: 'Resolution (DPI)', type: 'select', options: ['72', '150', '300'], defaultValue: '150' },
    ],
    outputExt: 'zip',
    tips: ['150 DPI is recommended for web use', '300 DPI produces print-quality images', 'Multiple pages are delivered as a ZIP archive'],
    relatedSlugs: ['jpg-to-pdf', 'compress', 'split'],
  },
  'jpg-to-pdf': {
    slug: 'jpg-to-pdf',
    label: 'JPG to PDF',
    tagline: 'Bind images into one scroll',
    description: 'Convert single or multiple JPG images into a PDF. Adjust orientation and margins — create a perfect multi-page image document.',
    category: 'Convert',
    type: 'easy',
    icon: '⊟',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/jpg-to-pdf',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/bmp'],
    acceptedLabel: 'JPG, PNG, BMP images',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload multiple images to create a multi-page PDF', 'Images are arranged in upload order', 'PNG and BMP images are also supported'],
    relatedSlugs: ['pdf-to-jpg', 'merge', 'compress'],
  },
  'html-to-pdf': {
    slug: 'html-to-pdf',
    label: 'HTML to PDF',
    tagline: 'Capture webpages with precision',
    description: 'Convert any webpage or HTML content to PDF. Paste a URL or raw HTML — we render it with full CSS support and save it to PDF.',
    category: 'Convert',
    type: 'easy',
    icon: '⊙',
    ninjaWeapon: 'Grappling Hook',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/html-to-pdf',
    acceptedTypes: ['text/html'],
    acceptedLabel: 'HTML files or URL',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Enter a URL to convert any webpage', 'Or paste raw HTML for direct conversion', 'Best for documentation pages, reports, and articles'],
    relatedSlugs: ['jpg-to-pdf', 'compress', 'word-to-pdf'],
  },
  watermark: {
    slug: 'watermark',
    label: 'Watermark PDF',
    tagline: 'Brand every page with your mark',
    description: 'Stamp text or an image watermark on your PDF. Control opacity, position, and typography — mark your document as yours.',
    category: 'Edit',
    type: 'easy',
    icon: '◎',
    ninjaWeapon: 'Ink Brush',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/watermark',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'text', label: 'Watermark Text', type: 'text', placeholder: 'e.g. CONFIDENTIAL' },
      { key: 'opacity', label: 'Opacity (0.1 - 1.0)', type: 'number', defaultValue: 0.3, min: 0.1, max: 1 },
    ],
    outputExt: 'pdf',
    tips: ['Use CONFIDENTIAL, DRAFT, or your company name', 'Lower opacity (0.1-0.3) gives a subtle watermark', 'The watermark appears on every page'],
    relatedSlugs: ['protect', 'rotate', 'page-numbers'],
  },
  rotate: {
    slug: 'rotate',
    label: 'Rotate PDF',
    tagline: 'Find the right angle',
    description: 'Rotate pages 90°, 180° or 270° — all pages or a specific selection. A ninja adjusts to every angle to find the perfect strike.',
    category: 'Edit',
    type: 'easy',
    icon: '↻',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/rotate',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'angle', label: 'Rotation Angle', type: 'select', options: ['90', '180', '270'], defaultValue: '90' },
      { key: 'pages', label: 'Apply to Pages', type: 'text', placeholder: 'all (or 1,3,5)', defaultValue: 'all' },
    ],
    outputExt: 'pdf',
    tips: ['Enter "all" to rotate every page', 'Specify page numbers like "1,3,5" for selective rotation', '90° clockwise is the most common rotation'],
    relatedSlugs: ['organize', 'crop', 'merge'],
  },
  crop: {
    slug: 'crop',
    label: 'Crop PDF',
    tagline: 'Remove the unnecessary',
    description: 'Trim margins or select specific content areas. Apply cropping to individual pages or the entire document — like cutting away the excess.',
    category: 'Edit',
    type: 'easy',
    icon: '⊡',
    ninjaWeapon: 'Chakram',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/crop',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'left', label: 'Left margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'bottom', label: 'Bottom margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'right', label: 'Right margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'top', label: 'Top margin (pts)', type: 'number', defaultValue: 0, min: 0 },
    ],
    outputExt: 'pdf',
    tips: ['Margins are measured in PDF points (1pt = 1/72 inch)', '72 points = 1 inch of margin removed', 'Start with small values and adjust as needed'],
    relatedSlugs: ['rotate', 'organize', 'split'],
  },
  'page-numbers': {
    slug: 'page-numbers',
    label: 'Page Numbers',
    tagline: 'Number your pages with honor',
    description: 'Add professional page numbers to your PDF. Choose position, font size, and starting number — applied with precision to every page.',
    category: 'Edit',
    type: 'easy',
    icon: '⊕',
    ninjaWeapon: 'Ink Brush',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/page-numbers',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'position', label: 'Position', type: 'select', options: ['bottom-center', 'bottom-right', 'bottom-left', 'top-center', 'top-right', 'top-left'], defaultValue: 'bottom-center' },
      { key: 'start', label: 'Start Number', type: 'number', defaultValue: 1, min: 1 },
      { key: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12, min: 8, max: 24 },
    ],
    outputExt: 'pdf',
    tips: ['Bottom-center is the most professional placement', 'Use "Start Number" to continue numbering from a previous document', 'Font size 10-12 is ideal for most documents'],
    relatedSlugs: ['watermark', 'organize', 'merge'],
  },
  protect: {
    slug: 'protect',
    label: 'Protect PDF',
    tagline: 'Shield your secrets',
    description: 'Encrypt your PDF with a password. Unauthorized access is forbidden — only those with the password can open the document.',
    category: 'Security',
    type: 'easy',
    icon: '🔒',
    ninjaWeapon: 'Iron Shield',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/protect',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'password', label: 'Password', type: 'text', placeholder: 'Enter a strong password' },
    ],
    outputExt: 'pdf',
    tips: ['Use a strong password with mixed characters', 'Store your password safely — we cannot recover it', 'AES-128 encryption is applied by default'],
    relatedSlugs: ['unlock', 'watermark', 'pdf-to-pdfa'],
  },
  unlock: {
    slug: 'unlock',
    label: 'Unlock PDF',
    tagline: 'Break the chains',
    description: 'Remove password protection from your PDF. Gain the freedom to edit, print, and share — like a ninja escaping any trap.',
    category: 'Security',
    type: 'easy',
    icon: '🔓',
    ninjaWeapon: 'Lock Pick',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/unlock',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'password', label: 'Current Password', type: 'text', placeholder: 'Enter the PDF password' },
    ],
    outputExt: 'pdf',
    tips: ['You must know the password to unlock the file', 'The resulting PDF will have no password restriction', 'We do not store passwords after processing'],
    relatedSlugs: ['protect', 'repair', 'compress'],
  },
  'scan-to-pdf': {
    slug: 'scan-to-pdf',
    label: 'Scan to PDF',
    tagline: 'Mobile capture → perfect PDF',
    description: 'Upload photos taken from your phone or scanner. We\'ll convert them into a clean, multi-page PDF document instantly.',
    category: 'Security',
    type: 'heavy',
    icon: '📷',
    ninjaWeapon: 'Spy Lens',
    ninjaImage: '/ninja_ocr.png',
    apiPath: '/v1/jobs/scan-to-pdf',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/tiff', 'image/bmp'],
    acceptedLabel: 'JPG, PNG, TIFF images',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload multiple scan images to merge into one PDF', 'Ensure good lighting for best OCR results', 'TIFF format is supported for high-resolution scans'],
    relatedSlugs: ['ocr', 'jpg-to-pdf', 'compress'],
  },
  ocr: {
    slug: 'ocr',
    label: 'OCR PDF',
    tagline: 'Read the unreadable',
    description: 'Extract text from scanned PDFs and images using AWS Textract AI. Turn a photo of a document into searchable, selectable text.',
    category: 'Security',
    type: 'ocr',
    icon: '👁',
    ninjaWeapon: 'Cybernetic Eye',
    ninjaImage: '/ninja_ocr.png',
    apiPath: '/v1/ocr',
    acceptedTypes: ['application/pdf', 'image/jpeg', 'image/png', 'image/tiff'],
    acceptedLabel: 'PDF, JPG, PNG or TIFF',
    multiFile: false,
    outputExt: 'txt',
    tips: ['Supports 9 languages including English, Japanese, and more', 'PDFs under 5MB are processed synchronously (faster)', 'Larger PDFs use async Textract (may take up to 90 seconds)'],
    relatedSlugs: ['scan-to-pdf', 'pdf-to-word', 'compress'],
  },
  'delete-pages': {
    slug: 'delete-pages',
    label: 'Delete Pages',
    tagline: 'Remove unwanted pages',
    description: 'Delete specific pages from your PDF file. Keep only what you need.',
    category: 'Organize',
    type: 'easy',
    icon: '🗑️',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/delete-pages',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "pages", "label": "Pages to delete", "type": "text", "placeholder": "e.g. 1, 3-5"},
    ],
    outputExt: 'pdf',
    tips: ["Use comma-separated numbers", "Ranges like 3-5 are supported", "Original is never altered"],
    relatedSlugs: ["split", "extract-pages", "organize"],
  },
  'extract-pages': {
    slug: 'extract-pages',
    label: 'Extract Pages',
    tagline: 'Pull out what you need',
    description: 'Extract specific pages from a large PDF to create a new document.',
    category: 'Organize',
    type: 'easy',
    icon: '✂️',
    ninjaWeapon: 'Kunai',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/extract-pages',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "pages", "label": "Pages to extract", "type": "text", "placeholder": "e.g. 1, 3-5"},
    ],
    outputExt: 'pdf',
    tips: ["Use comma-separated numbers", "Creates a single PDF from extracted pages", "Perfect for sharing subsets of documents"],
    relatedSlugs: ["delete-pages", "split", "organize"],
  },
  'pdf-to-png': {
    slug: 'pdf-to-png',
    label: 'PDF to PNG',
    tagline: 'Pixel-perfect image extraction',
    description: 'Convert PDF pages into high-quality PNG images with transparent backgrounds supported.',
    category: 'Convert',
    type: 'easy',
    icon: '🖼️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/pdf-to-png',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "dpi", "label": "Resolution (DPI)", "type": "select", "options": ["72", "150", "300"], "defaultValue": "150"},
    ],
    outputExt: 'zip',
    tips: ["300 DPI is best for high resolution", "Images are delivered in a ZIP file", "Great for presentations and web graphics"],
    relatedSlugs: ["pdf-to-jpg", "jpg-to-png", "pdf-to-tiff"],
  },
  'pdf-to-tiff': {
    slug: 'pdf-to-tiff',
    label: 'PDF to TIFF',
    tagline: 'Archival quality images',
    description: 'Convert PDF files into TIFF format for high-quality printing and archiving.',
    category: 'Convert',
    type: 'easy',
    icon: '🎞️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/pdf-to-tiff',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "dpi", "label": "Resolution (DPI)", "type": "select", "options": ["150", "200", "300", "600"], "defaultValue": "200"},
    ],
    outputExt: 'tiff',
    tips: ["TIFF is excellent for faxing and printing", "Higher DPI means larger file size", "Produces multi-page TIFF if PDF has multiple pages"],
    relatedSlugs: ["pdf-to-png", "pdf-to-jpg", "tiff-to-jpg"],
  },
  'flatten-pdf': {
    slug: 'flatten-pdf',
    label: 'Flatten PDF',
    tagline: 'Make your PDF uneditable',
    description: 'Flatten form fields, annotations, and layers into a single static layer to prevent future edits.',
    category: 'Edit',
    type: 'easy',
    icon: '🔨',
    ninjaWeapon: 'Hammer',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/flatten-pdf',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Ensures form fields can no longer be edited", "Locks comments and stamps", "Good for sharing finalized documents"],
    relatedSlugs: ["protect", "pdf-to-pdfa", "compress"],
  },
  'remove-metadata': {
    slug: 'remove-metadata',
    label: 'Remove Metadata',
    tagline: 'Sanitize your document',
    description: 'Strip hidden metadata, author details, creation dates, and tracker info from your PDF.',
    category: 'Security',
    type: 'easy',
    icon: '🧹',
    ninjaWeapon: 'Broom',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/remove-metadata',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Removes Author, Title, Subject, and Keywords", "Cleans hidden object properties", "Crucial for privacy before sharing"],
    relatedSlugs: ["flatten-pdf", "pdf-redact", "protect"],
  },
  'reverse-pages': {
    slug: 'reverse-pages',
    label: 'Reverse Pages',
    tagline: 'Flip the order',
    description: 'Instantly reverse the page order of your PDF document (e.g., from 1-10 to 10-1).',
    category: 'Organize',
    type: 'easy',
    icon: '🔄',
    ninjaWeapon: 'Boomerang',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/reverse-pages',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Useful for documents scanned in reverse", "Takes seconds to process", "Reorders exactly backwards"],
    relatedSlugs: ["organize", "split", "delete-pages"],
  },
  'grayscale-pdf': {
    slug: 'grayscale-pdf',
    label: 'Grayscale PDF',
    tagline: 'Remove all color',
    description: 'Convert your color PDF into black and white (grayscale) to save ink and reduce file size.',
    category: 'Optimize',
    type: 'easy',
    icon: '⚫',
    ninjaWeapon: 'Ink',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/grayscale-pdf',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Perfect for printing documents", "Often reduces file size", "Text remains sharp and clear"],
    relatedSlugs: ["compress", "image-to-grayscale", "pdf-to-pdfa"],
  },
  'linearize-pdf': {
    slug: 'linearize-pdf',
    label: 'Linearize PDF',
    tagline: 'Optimize for web viewing',
    description: 'Fast Web View enable your PDF so it loads instantly in web browsers without downloading the full file.',
    category: 'Optimize',
    type: 'easy',
    icon: '⚡',
    ninjaWeapon: 'Lightning',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/linearize-pdf',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Essential for PDFs hosted on websites", "Also known as 'Fast Web View'", "Restructures file for byte-serving"],
    relatedSlugs: ["compress", "compress-to-size", "pdf-info"],
  },
  'n-up-pdf': {
    slug: 'n-up-pdf',
    label: 'N-Up PDF',
    tagline: 'Multiple pages per sheet',
    description: 'Combine multiple PDF pages onto a single page (2-up, 4-up) for efficient printing and reviewing.',
    category: 'Organize',
    type: 'easy',
    icon: '🗂️',
    ninjaWeapon: 'Origami',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/n-up-pdf',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "n", "label": "Pages per sheet", "type": "select", "options": ["2", "4", "8", "16"], "defaultValue": "2"},
    ],
    outputExt: 'pdf',
    tips: ["Saves paper when printing", "Automatically scales pages to fit", "Creates a handout-style layout"],
    relatedSlugs: ["merge", "resize-pages", "organize"],
  },
  'add-text': {
    slug: 'add-text',
    label: 'Add Text',
    tagline: 'Write directly on PDF',
    description: 'Add custom text strings at specific coordinates on your PDF pages.',
    category: 'Edit',
    type: 'easy',
    icon: '✍️',
    ninjaWeapon: 'Pen',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/add-text',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "text", "label": "Text to add", "type": "text", "placeholder": "Enter text"},
      {"key": "page", "label": "Page Number", "type": "number", "defaultValue": 1},
      {"key": "x", "label": "X Position (pts)", "type": "number", "defaultValue": 100},
      {"key": "y", "label": "Y Position (pts)", "type": "number", "defaultValue": 100},
      {"key": "font_size", "label": "Font Size", "type": "number", "defaultValue": 12},
    ],
    outputExt: 'pdf',
    tips: ["Coordinates are measured from bottom-left", "Font size is in points", "Useful for filling static forms"],
    relatedSlugs: ["watermark", "add-header-footer", "add-signature-box"],
  },
  'add-header-footer': {
    slug: 'add-header-footer',
    label: 'Add Header & Footer',
    tagline: 'Professional document branding',
    description: 'Add customized headers and footers to every page of your PDF document.',
    category: 'Edit',
    type: 'easy',
    icon: '📑',
    ninjaWeapon: 'Stamp',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/add-header-footer',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "header", "label": "Header Text", "type": "text", "placeholder": "e.g. Annual Report"},
      {"key": "footer", "label": "Footer Text", "type": "text", "placeholder": "e.g. Page {n} of {total}"},
      {"key": "font_size", "label": "Font Size", "type": "number", "defaultValue": 10},
    ],
    outputExt: 'pdf',
    tips: ["Use {n} for current page number", "Use {total} for total pages", "Applies to the entire document automatically"],
    relatedSlugs: ["page-numbers", "watermark", "add-text"],
  },
  'pdf-redact': {
    slug: 'pdf-redact',
    label: 'Redact PDF',
    tagline: 'Permanently black out text',
    description: 'Securely black out sensitive information and images from your PDF files.',
    category: 'Security',
    type: 'easy',
    icon: '⬛',
    ninjaWeapon: 'Black Ink',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/pdf-redact',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "page", "label": "Page Number", "type": "number", "defaultValue": 1},
      {"key": "x", "label": "X Position", "type": "number", "defaultValue": 100},
      {"key": "y", "label": "Y Position", "type": "number", "defaultValue": 100},
      {"key": "width", "label": "Width", "type": "number", "defaultValue": 200},
      {"key": "height", "label": "Height", "type": "number", "defaultValue": 30},
    ],
    outputExt: 'pdf',
    tips: ["Redaction is permanent and cannot be undone", "Removes hidden text behind the blackout", "Coordinates are from bottom-left"],
    relatedSlugs: ["remove-metadata", "flatten-pdf", "protect"],
  },
  'resize-pages': {
    slug: 'resize-pages',
    label: 'Resize Pages',
    tagline: 'Change document dimensions',
    description: 'Resize your PDF pages to standard paper sizes like A4, Letter, Legal, or A3.',
    category: 'Edit',
    type: 'easy',
    icon: '📏',
    ninjaWeapon: 'Ruler',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/resize-pages',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "size", "label": "Page Size", "type": "select", "options": ["A4", "Letter", "A3", "Legal", "A5"], "defaultValue": "A4"},
      {"key": "orientation", "label": "Orientation", "type": "select", "options": ["portrait", "landscape"], "defaultValue": "portrait"},
    ],
    outputExt: 'pdf',
    tips: ["Scales content to fit the new size", "A4 is standard in Europe/Asia", "Letter is standard in North America"],
    relatedSlugs: ["crop", "compress-to-size", "n-up-pdf"],
  },
  'add-signature-box': {
    slug: 'add-signature-box',
    label: 'Add Signature Box',
    tagline: 'Prepare for signing',
    description: 'Add a professional signature line and box for physical or digital signing.',
    category: 'Edit',
    type: 'easy',
    icon: '📝',
    ninjaWeapon: 'Seal',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/add-signature-box',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "page", "label": "Page Number", "type": "number", "defaultValue": 1},
      {"key": "label", "label": "Signature Label", "type": "text", "defaultValue": "Authorized Signatory"},
    ],
    outputExt: 'pdf',
    tips: ["Adds an 'X' and a dotted line", "Creates a clear space for signatures", "Can include a date line automatically"],
    relatedSlugs: ["add-text", "flatten-pdf", "protect"],
  },
  'pdf-info': {
    slug: 'pdf-info',
    label: 'PDF Info',
    tagline: 'Inspect PDF metadata',
    description: 'Extract detailed information about your PDF including page count, sizes, and hidden metadata.',
    category: 'Security',
    type: 'easy',
    icon: 'ℹ️',
    ninjaWeapon: 'Magnifying Glass',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/pdf-info',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'json',
    tips: ["Returns data instantly", "Shows if file is encrypted", "Displays exact page dimensions"],
    relatedSlugs: ["remove-metadata", "linearize-pdf", "compress"],
  },
  'png-to-jpg': {
    slug: 'png-to-jpg',
    label: 'PNG to JPG',
    tagline: 'Convert PNG images to JPG',
    description: 'Instantly convert your PNG files to JPG format. Reduce file size while keeping visual quality.',
    category: 'Convert',
    type: 'easy',
    icon: '🖼️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/png-to-jpg',
    acceptedTypes: ["image/png"],
    acceptedLabel: 'PNG files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "JPG Quality (1-100)", "type": "number", "defaultValue": 90, "min": 1, "max": 100},
    ],
    outputExt: 'jpg',
    tips: ["JPGs are smaller but don't support transparency", "Quality 90 is recommended for best balance", "Transparency will be replaced with white background"],
    relatedSlugs: ["jpg-to-png", "image-compress", "webp-to-jpg"],
  },
  'jpg-to-png': {
    slug: 'jpg-to-png',
    label: 'JPG to PNG',
    tagline: 'Convert JPG images to PNG',
    description: 'Convert JPG photos and graphics into high-quality PNG format.',
    category: 'Convert',
    type: 'easy',
    icon: '🖼️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/jpg-to-png',
    acceptedTypes: ["image/jpeg"],
    acceptedLabel: 'JPG files only',
    multiFile: false,
    outputExt: 'png',
    tips: ["Lossless conversion preserves original quality", "PNG format allows for future transparency edits", "File size may increase after conversion"],
    relatedSlugs: ["png-to-jpg", "jpg-to-webp", "image-resize"],
  },
  'webp-to-jpg': {
    slug: 'webp-to-jpg',
    label: 'WebP to JPG',
    tagline: 'Make WebP images compatible',
    description: 'Convert modern WebP images to universally supported JPG format.',
    category: 'Convert',
    type: 'easy',
    icon: '🕸️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/webp-to-jpg',
    acceptedTypes: ["image/webp"],
    acceptedLabel: 'WebP files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "JPG Quality", "type": "number", "defaultValue": 90},
    ],
    outputExt: 'jpg',
    tips: ["Essential for older software that doesn't support WebP", "Quick and seamless conversion", "Animations in WebP are not preserved"],
    relatedSlugs: ["webp-to-png", "jpg-to-webp", "png-to-webp"],
  },
  'webp-to-png': {
    slug: 'webp-to-png',
    label: 'WebP to PNG',
    tagline: 'Convert WebP with transparency',
    description: 'Convert WebP images to standard PNG format while preserving transparent backgrounds.',
    category: 'Convert',
    type: 'easy',
    icon: '🕸️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/webp-to-png',
    acceptedTypes: ["image/webp"],
    acceptedLabel: 'WebP files only',
    multiFile: false,
    outputExt: 'png',
    tips: ["Maintains image transparency (alpha channel)", "Lossless conversion", "Perfect for web designers"],
    relatedSlugs: ["webp-to-jpg", "png-to-webp", "png-to-jpg"],
  },
  'jpg-to-webp': {
    slug: 'jpg-to-webp',
    label: 'JPG to WebP',
    tagline: 'Next-gen image optimization',
    description: 'Convert JPG images to Google\'s WebP format for superior web compression and faster loading.',
    category: 'Convert',
    type: 'easy',
    icon: '🕸️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/jpg-to-webp',
    acceptedTypes: ["image/jpeg"],
    acceptedLabel: 'JPG files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality", "type": "number", "defaultValue": 85},
    ],
    outputExt: 'webp',
    tips: ["WebP is ~30% smaller than JPG for the same quality", "Supported by all modern web browsers", "Improves your website's Core Web Vitals"],
    relatedSlugs: ["png-to-webp", "webp-to-jpg", "image-compress"],
  },
  'png-to-webp': {
    slug: 'png-to-webp',
    label: 'PNG to WebP',
    tagline: 'Optimize PNGs for the web',
    description: 'Convert PNG files to WebP to drastically reduce file size while keeping transparency.',
    category: 'Convert',
    type: 'easy',
    icon: '🕸️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/png-to-webp',
    acceptedTypes: ["image/png"],
    acceptedLabel: 'PNG files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality", "type": "number", "defaultValue": 85},
    ],
    outputExt: 'webp',
    tips: ["Preserves transparency channels", "Massive file size reduction compared to PNG", "Essential for SEO image optimization"],
    relatedSlugs: ["jpg-to-webp", "webp-to-png", "image-compress"],
  },
  'heic-to-jpg': {
    slug: 'heic-to-jpg',
    label: 'HEIC to JPG',
    tagline: 'Convert iPhone photos',
    description: 'Convert Apple\'s HEIC/HEIF image format to standard JPG for compatibility on Windows and Android.',
    category: 'Convert',
    type: 'easy',
    icon: '📱',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/heic-to-jpg',
    acceptedTypes: ["image/heic", "image/heif"],
    acceptedLabel: 'HEIC/HEIF files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality", "type": "number", "defaultValue": 90},
    ],
    outputExt: 'jpg',
    tips: ["Solves compatibility issues with iPhone photos", "Fast and secure conversion", "EXIF data (location, time) may be altered"],
    relatedSlugs: ["heic-to-png", "jpg-to-png", "image-compress"],
  },
  'heic-to-png': {
    slug: 'heic-to-png',
    label: 'HEIC to PNG',
    tagline: 'HEIC to lossless PNG',
    description: 'Convert iPhone HEIC photos to high-quality lossless PNG format.',
    category: 'Convert',
    type: 'easy',
    icon: '📱',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/heic-to-png',
    acceptedTypes: ["image/heic", "image/heif"],
    acceptedLabel: 'HEIC/HEIF files only',
    multiFile: false,
    outputExt: 'png',
    tips: ["Best for editing iPhone photos on PC", "Lossless conversion", "File sizes will be significantly larger than HEIC"],
    relatedSlugs: ["heic-to-jpg", "png-to-jpg", "image-to-size"],
  },
  'bmp-to-jpg': {
    slug: 'bmp-to-jpg',
    label: 'BMP to JPG',
    tagline: 'Compress bitmap images',
    description: 'Convert uncompressed BMP files into standard, web-friendly JPG format.',
    category: 'Convert',
    type: 'easy',
    icon: '🖼️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/bmp-to-jpg',
    acceptedTypes: ["image/bmp"],
    acceptedLabel: 'BMP files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality", "type": "number", "defaultValue": 90},
    ],
    outputExt: 'jpg',
    tips: ["Dramatically reduces file size", "Makes BMPs shareable online", "Quality 90 provides excellent visual fidelity"],
    relatedSlugs: ["bmp-to-png", "png-to-jpg", "image-compress"],
  },
  'bmp-to-png': {
    slug: 'bmp-to-png',
    label: 'BMP to PNG',
    tagline: 'Modernize bitmap images',
    description: 'Convert older BMP files into modern, lossless PNG format.',
    category: 'Convert',
    type: 'easy',
    icon: '🖼️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/bmp-to-png',
    acceptedTypes: ["image/bmp"],
    acceptedLabel: 'BMP files only',
    multiFile: false,
    outputExt: 'png',
    tips: ["Lossless compression", "Smaller file size than BMP without losing quality", "Better compatibility across modern devices"],
    relatedSlugs: ["bmp-to-jpg", "jpg-to-png", "image-resize"],
  },
  'tiff-to-jpg': {
    slug: 'tiff-to-jpg',
    label: 'TIFF to JPG',
    tagline: 'Convert high-res TIFFs',
    description: 'Convert large TIFF printing files into manageable JPG images for easy viewing and sharing.',
    category: 'Convert',
    type: 'easy',
    icon: '🎞️',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/tiff-to-jpg',
    acceptedTypes: ["image/tiff"],
    acceptedLabel: 'TIFF files only',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality", "type": "number", "defaultValue": 90},
    ],
    outputExt: 'zip',
    tips: ["Massively reduces file size", "If TIFF is multi-page, outputs a ZIP of JPGs", "Great for emailing scanned documents"],
    relatedSlugs: ["pdf-to-tiff", "pdf-to-jpg", "image-compress"],
  },
  'svg-to-png': {
    slug: 'svg-to-png',
    label: 'SVG to PNG',
    tagline: 'Rasterize vector graphics',
    description: 'Convert scalable vector graphics (SVG) into standard PNG images.',
    category: 'Convert',
    type: 'easy',
    icon: '📐',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/svg-to-png',
    acceptedTypes: ["image/svg+xml"],
    acceptedLabel: 'SVG files only',
    multiFile: false,
    options: [
      {"key": "scale", "label": "Scale Factor", "type": "number", "defaultValue": 2.0},
      {"key": "width", "label": "Target Width", "type": "number", "defaultValue": 800},
    ],
    outputExt: 'png',
    tips: ["Converts vectors to pixels", "Increase scale factor for sharper images", "Preserves vector transparency"],
    relatedSlugs: ["png-to-jpg", "webp-to-png", "image-resize"],
  },
  'image-compress': {
    slug: 'image-compress',
    label: 'Compress Image',
    tagline: 'Reduce image file size',
    description: 'Optimize and compress JPG, PNG, and WebP images without noticeable quality loss.',
    category: 'Optimize',
    type: 'easy',
    icon: '🗜️',
    ninjaWeapon: 'Iron Fan',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/image-compress',
    acceptedTypes: ["image/jpeg", "image/png", "image/webp"],
    acceptedLabel: 'JPG, PNG, WebP',
    multiFile: false,
    options: [
      {"key": "quality", "label": "Quality (1-100)", "type": "number", "defaultValue": 75},
      {"key": "max_width", "label": "Max Width (px)", "type": "number", "defaultValue": 1920},
    ],
    outputExt: 'jpg',
    tips: ["Quality 75 is visually identical to original in most cases", "Resizing max width helps reduce size further", "Essential for website performance"],
    relatedSlugs: ["compress", "image-to-size", "compress-to-size"],
  },
  'image-resize': {
    slug: 'image-resize',
    label: 'Resize Image',
    tagline: 'Change image dimensions',
    description: 'Resize your image to exact pixel dimensions or scale by percentage.',
    category: 'Edit',
    type: 'easy',
    icon: '📏',
    ninjaWeapon: 'Ruler',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/image-resize',
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/bmp"],
    acceptedLabel: 'Images',
    multiFile: false,
    options: [
      {"key": "width", "label": "Width", "type": "number", "defaultValue": 800},
      {"key": "height", "label": "Height", "type": "number", "defaultValue": 600},
      {"key": "mode", "label": "Resize Mode", "type": "select", "options": ["fit", "exact", "fill"], "defaultValue": "fit"},
    ],
    outputExt: 'jpg',
    tips: ["'Fit' preserves aspect ratio", "'Exact' ignores aspect ratio and forces dimensions", "Useful for social media covers and posts"],
    relatedSlugs: ["image-crop", "resize-to-passport", "image-compress"],
  },
  'image-crop': {
    slug: 'image-crop',
    label: 'Crop Image',
    tagline: 'Cut out the rest',
    description: 'Crop images by specifying exact pixel coordinates and dimensions.',
    category: 'Edit',
    type: 'easy',
    icon: '✂️',
    ninjaWeapon: 'Kunai',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/image-crop',
    acceptedTypes: ["image/jpeg", "image/png", "image/webp"],
    acceptedLabel: 'Images',
    multiFile: false,
    options: [
      {"key": "x", "label": "X Offset", "type": "number", "defaultValue": 0},
      {"key": "y", "label": "Y Offset", "type": "number", "defaultValue": 0},
      {"key": "width", "label": "Width", "type": "number", "defaultValue": 500},
      {"key": "height", "label": "Height", "type": "number", "defaultValue": 500},
    ],
    outputExt: 'jpg',
    tips: ["X and Y start from the top-left corner", "Removes unwanted outer areas", "Values must be in pixels"],
    relatedSlugs: ["image-resize", "crop", "image-to-size"],
  },
  'image-to-grayscale': {
    slug: 'image-to-grayscale',
    label: 'Image to Grayscale',
    tagline: 'Black & white photos',
    description: 'Convert any color image into a classic black and white grayscale photo.',
    category: 'Optimize',
    type: 'easy',
    icon: '⚫',
    ninjaWeapon: 'Ink',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/image-to-grayscale',
    acceptedTypes: ["image/jpeg", "image/png", "image/webp"],
    acceptedLabel: 'Images',
    multiFile: false,
    outputExt: 'jpg',
    tips: ["Creates artistic black and white effects", "Slightly reduces file size", "Removes all color data permanently"],
    relatedSlugs: ["grayscale-pdf", "image-compress", "png-to-jpg"],
  },
  'compress-to-size': {
    slug: 'compress-to-size',
    label: 'Compress PDF to Size',
    tagline: 'Exact file sizes',
    description: 'Compress your PDF file to be exactly under a specific size (e.g. under 200KB) for government portals.',
    category: 'Optimize',
    type: 'heavy',
    icon: '🗜️',
    ninjaWeapon: 'Iron Fan',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/compress-to-size',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      {"key": "target_kb", "label": "Target Size (KB)", "type": "number", "defaultValue": 200},
    ],
    outputExt: 'pdf',
    tips: ["Perfect for IRCTC, Passport Seva, and Govt portals", "May reduce visual quality to hit aggressive targets", "100KB to 500KB are common requirements"],
    relatedSlugs: ["compress", "image-to-size", "resize-to-passport"],
  },
  'image-to-size': {
    slug: 'image-to-size',
    label: 'Compress Image to Size',
    tagline: 'Exact image sizes',
    description: 'Compress JPG or PNG images to be exactly under a required file size in KB.',
    category: 'Optimize',
    type: 'easy',
    icon: '🗜️',
    ninjaWeapon: 'Iron Fan',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/image-to-size',
    acceptedTypes: ["image/jpeg", "image/png"],
    acceptedLabel: 'JPG, PNG',
    multiFile: false,
    options: [
      {"key": "target_kb", "label": "Target Size (KB)", "type": "number", "defaultValue": 50},
      {"key": "format", "label": "Output Format", "type": "select", "options": ["jpg", "png"], "defaultValue": "jpg"},
    ],
    outputExt: 'jpg',
    tips: ["Great for uploading signatures and photos to portals", "JPG usually achieves smaller sizes than PNG", "Algorithms will find the best quality for your target size"],
    relatedSlugs: ["image-compress", "compress-to-size", "resize-to-passport"],
  },
  'resize-to-passport': {
    slug: 'resize-to-passport',
    label: 'Passport Photo Maker',
    tagline: 'Official photo sizes',
    description: 'Automatically resize and crop your photo to official passport/visa dimensions (India, US, UK, etc.).',
    category: 'Edit',
    type: 'easy',
    icon: '📸',
    ninjaWeapon: 'Spy Lens',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/resize-to-passport',
    acceptedTypes: ["image/jpeg", "image/png"],
    acceptedLabel: 'Images',
    multiFile: false,
    options: [
      {"key": "size", "label": "Passport Standard", "type": "select", "options": ["india_passport", "us_passport", "uk_visa", "schengen_visa", "china_visa"], "defaultValue": "india_passport"},
      {"key": "dpi", "label": "DPI (Print Quality)", "type": "number", "defaultValue": 300},
    ],
    outputExt: 'jpg',
    tips: ["India Passport: 35x45mm", "US Passport: 51x51mm (2x2 inch)", "Outputs high-res JPG ready for printing"],
    relatedSlugs: ["image-to-size", "image-crop", "image-resize"],
  },
  'txt-to-pdf': {
    slug: 'txt-to-pdf',
    label: 'TXT to PDF',
    tagline: 'Plain text to PDF',
    description: 'Convert plain text (.txt) files into clean, readable PDF documents.',
    category: 'Convert',
    type: 'heavy',
    icon: '📄',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/txt-to-pdf',
    acceptedTypes: ["text/plain"],
    acceptedLabel: 'TXT files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Maintains original formatting and line breaks", "Uses standard monospace or sans-serif fonts", "Perfect for logs and code snippets"],
    relatedSlugs: ["md-to-pdf", "rtf-to-pdf", "csv-to-pdf"],
  },
  'rtf-to-pdf': {
    slug: 'rtf-to-pdf',
    label: 'RTF to PDF',
    tagline: 'Rich text to PDF',
    description: 'Convert Rich Text Format (.rtf) files to universally compatible PDFs.',
    category: 'Convert',
    type: 'heavy',
    icon: '📝',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/rtf-to-pdf',
    acceptedTypes: ["application/rtf"],
    acceptedLabel: 'RTF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Preserves bold, italics, and text sizing", "Excellent alternative to Word conversions", "Works flawlessly on all devices"],
    relatedSlugs: ["word-to-pdf", "txt-to-pdf", "odt-to-pdf"],
  },
  'odt-to-pdf': {
    slug: 'odt-to-pdf',
    label: 'ODT to PDF',
    tagline: 'OpenOffice to PDF',
    description: 'Convert OpenDocument Text (.odt) files from LibreOffice or OpenOffice into PDF format.',
    category: 'Convert',
    type: 'heavy',
    icon: '📝',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/odt-to-pdf',
    acceptedTypes: ["application/vnd.oasis.opendocument.text"],
    acceptedLabel: 'ODT files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Native LibreOffice rendering ensures 100% fidelity", "Preserves layouts, images, and tables", "Fast and secure processing"],
    relatedSlugs: ["word-to-pdf", "rtf-to-pdf", "pdf-to-word"],
  },
  'csv-to-pdf': {
    slug: 'csv-to-pdf',
    label: 'CSV to PDF',
    tagline: 'Spreadsheets to PDF',
    description: 'Convert Comma Separated Values (.csv) files into neatly formatted PDF tables.',
    category: 'Convert',
    type: 'heavy',
    icon: '📊',
    ninjaWeapon: 'Naginata',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/csv-to-pdf',
    acceptedTypes: ["text/csv"],
    acceptedLabel: 'CSV files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Formats data into a clean, readable grid", "Auto-adjusts column widths", "Much easier to share and print than raw CSV"],
    relatedSlugs: ["excel-to-pdf", "pdf-to-excel", "txt-to-pdf"],
  },
  'epub-to-pdf': {
    slug: 'epub-to-pdf',
    label: 'EPUB to PDF',
    tagline: 'Ebooks to PDF',
    description: 'Convert EPUB ebook files into PDF documents so you can read them on any device.',
    category: 'Convert',
    type: 'heavy',
    icon: '📖',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/epub-to-pdf',
    acceptedTypes: ["application/epub+zip"],
    acceptedLabel: 'EPUB files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Generates standard book pagination", "Embeds all book fonts and images", "Makes ebooks printable and shareable"],
    relatedSlugs: ["pdf-to-pdfa", "txt-to-pdf", "md-to-pdf"],
  },
  'md-to-pdf': {
    slug: 'md-to-pdf',
    label: 'Markdown to PDF',
    tagline: 'Render Markdown to PDF',
    description: 'Convert Markdown (.md) files into beautifully formatted PDF documents.',
    category: 'Convert',
    type: 'heavy',
    icon: 'Ⓜ️',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/md-to-pdf',
    acceptedTypes: ["text/markdown"],
    acceptedLabel: 'MD files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ["Renders headings, lists, and code blocks perfectly", "Great for developer documentation", "Produces clean, minimalist output"],
    relatedSlugs: ["txt-to-pdf", "html-to-pdf", "rtf-to-pdf"],
  },
  'pdf-to-txt': {
    slug: 'pdf-to-txt',
    label: 'PDF to TXT',
    tagline: 'Extract raw text',
    description: 'Extract all plain text from a PDF document into a simple .txt file.',
    category: 'Convert',
    type: 'heavy',
    icon: '📄',
    ninjaWeapon: 'Tanto',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-txt',
    acceptedTypes: ["application/pdf"],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'txt',
    tips: ["Strips away all formatting and images", "Fastest way to get text from a large document", "Does not perform OCR on scanned images"],
    relatedSlugs: ["pdf-to-word", "txt-to-pdf", "ocr"],
  },
};

export const TOOL_LIST = Object.values(TOOLS);

export function getRelatedTools(slug: string): ToolConfig[] {
  const tool = TOOLS[slug];
  if (!tool) return [];
  return tool.relatedSlugs.map(s => TOOLS[s]).filter(Boolean);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOL_LIST.filter(t => t.category === category);
}

export const CATEGORY_META: Record<ToolCategory, { label: string; desc: string; icon: string }> = {
  Organize: { label: 'Organize PDF', desc: 'Arrange and restructure your documents', icon: '⊞' },
  Optimize: { label: 'Optimize PDF', desc: 'Compress, repair, and archive your files', icon: '↘' },
  Convert:  { label: 'Convert PDF',  desc: 'Transform between file formats at ninja speed', icon: '⇒' },
  Edit:     { label: 'Edit PDF',     desc: 'Modify and customize your PDF content', icon: '✎' },
  Security: { label: 'PDF Security', desc: 'Protect, unlock, and extract from PDFs', icon: '🔒' },
};