export type ToolCategory = 'Organize' | 'Optimize' | 'Convert' | 'Edit' | 'Security';
export type ToolType = 'easy' | 'heavy' | 'ocr';

export interface ToolOption {
  key: string;
  label: string;
  type: 'select' | 'text' | 'number' | 'range';
  options?: string[];
  defaultValue?: string | number;
  min?: number;
  max?: number;
  placeholder?: string;
}

export interface ToolConfig {
  slug: string;
  label: string;
  tagline: string;
  description: string;
  category: ToolCategory;
  type: ToolType;
  icon: string;
  ninjaWeapon: string;
  ninjaImage: string;
  apiPath: string;
  acceptedTypes: string[];
  acceptedLabel: string;
  multiFile: boolean;
  options?: ToolOption[];
  outputExt: string;
  tips: string[];
  relatedSlugs: string[];
}

export const TOOLS: Record<string, ToolConfig> = {
  merge: {
    slug: 'merge',
    label: 'Merge PDF',
    tagline: 'Unite your scrolls into one',
    description: 'Combine multiple PDFs in the exact order you want. Drag to reorder, then strike — the result is a single, perfectly fused document.',
    category: 'Organize',
    type: 'easy',
    icon: '⊕',
    ninjaWeapon: 'Dual Katana',
    ninjaImage: '/ninja_merge.png',
    apiPath: '/v1/tools/merge',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload files in the order you want them merged', 'You can upload up to 20 PDFs at once', 'Files are deleted from our servers after 24 hours'],
    relatedSlugs: ['split', 'organize', 'compress'],
  },
  split: {
    slug: 'split',
    label: 'Split PDF',
    tagline: 'Slice with surgical precision',
    description: 'Cut your PDF into individual pages or custom ranges. Extract exactly what you need — like a throwing star hitting its mark.',
    category: 'Organize',
    type: 'easy',
    icon: '⊗',
    ninjaWeapon: 'Kunai',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/split',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'mode', label: 'Split Mode', type: 'select', options: ['all', 'range'], defaultValue: 'all' },
    ],
    outputExt: 'zip',
    tips: ['Choose "All Pages" to extract every page as a separate PDF', 'Use "Range" to extract specific page sets like 1-3, 5-7', 'Range format: use comma-separated ranges'],
    relatedSlugs: ['merge', 'organize', 'crop'],
  },
  organize: {
    slug: 'organize',
    label: 'Organize PDF',
    tagline: 'Master the order of your scrolls',
    description: 'Reorder, delete or arrange PDF pages with precision. Total control — like a ninja choreographing a perfect battle.',
    category: 'Organize',
    type: 'easy',
    icon: '⊞',
    ninjaWeapon: 'Nunchaku',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/organize',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Enter page numbers in the new order (e.g. 3,1,2,5)', 'Skip a page number to delete it', 'Use this after merging to perfect the sequence'],
    relatedSlugs: ['merge', 'split', 'rotate'],
  },
  compress: {
    slug: 'compress',
    label: 'Compress PDF',
    tagline: 'Reduce size, keep the power',
    description: 'Shrink your PDF file size by up to 70% while keeping visual quality intact. Swift, efficient — a ninja never carries excess weight.',
    category: 'Optimize',
    type: 'easy',
    icon: '↘',
    ninjaWeapon: 'Iron Fan',
    ninjaImage: '/ninja_compress.png',
    apiPath: '/v1/tools/compress',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'quality', label: 'Compression Level', type: 'select', options: ['screen', 'ebook', 'printer', 'prepress'], defaultValue: 'ebook' },
    ],
    outputExt: 'pdf',
    tips: ['"Ebook" quality is recommended — great balance of size and clarity', '"Screen" gives the smallest file, best for emails', '"Prepress" keeps highest quality for printing'],
    relatedSlugs: ['repair', 'pdf-to-pdfa', 'merge'],
  },
  repair: {
    slug: 'repair',
    label: 'Repair PDF',
    tagline: 'Restore what is broken',
    description: 'Recover data from damaged or corrupt PDF files. Even a fallen warrior can be revived — our repair tool finds and fixes structural errors.',
    category: 'Optimize',
    type: 'easy',
    icon: '⚙',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/repair',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Works on most structurally damaged PDFs', 'Cannot recover password-protected encrypted files', 'Try compress after repair to reduce any bloat'],
    relatedSlugs: ['compress', 'pdf-to-pdfa', 'unlock'],
  },
  'pdf-to-pdfa': {
    slug: 'pdf-to-pdfa',
    label: 'PDF to PDF/A',
    tagline: 'Archival-grade preservation',
    description: 'Convert your PDF to the ISO-standardized PDF/A format for long-term archiving. Your document will remain readable for generations to come.',
    category: 'Optimize',
    type: 'heavy',
    icon: '◈',
    ninjaWeapon: 'Scroll',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/jobs/pdf-to-pdfa',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['PDF/A is the standard for legal and government archiving', 'All fonts and colors are embedded for future compatibility', 'Larger file size is expected — this is by design'],
    relatedSlugs: ['compress', 'repair', 'protect'],
  },
  'pdf-to-word': {
    slug: 'pdf-to-word',
    label: 'PDF to Word',
    tagline: 'Unlock the content within',
    description: 'Transform any PDF into a fully editable DOC/DOCX file with ~85% layout fidelity. Extract text, tables, and formatting in seconds.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Tanto',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-word',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'docx',
    tips: ['Best results on text-based PDFs (not scanned images)', 'Run OCR first if your PDF is a scanned document', 'Complex layouts may need minor manual cleanup'],
    relatedSlugs: ['word-to-pdf', 'pdf-to-excel', 'ocr'],
  },
  'word-to-pdf': {
    slug: 'word-to-pdf',
    label: 'Word to PDF',
    tagline: 'Strike without mercy',
    description: 'Convert DOC and DOCX files to pixel-perfect PDFs using LibreOffice rendering. Preserve every font, table and image — no quality lost.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/word-to-pdf',
    acceptedTypes: ['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    acceptedLabel: 'DOC or DOCX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['All fonts and images are embedded in the output', 'Works with both .doc (old) and .docx (new) format', 'Processing typically takes 10-30 seconds'],
    relatedSlugs: ['pdf-to-word', 'compress', 'protect'],
  },
  'pdf-to-ppt': {
    slug: 'pdf-to-ppt',
    label: 'PDF to PowerPoint',
    tagline: 'Transform presentations instantly',
    description: 'Convert your PDF into PPT/PPTX slides. Each page becomes a visual slide — perfect for presentations that started as PDFs.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Kama',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-ppt',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'pptx',
    tips: ['Each PDF page becomes one presentation slide', 'Slides are image-based — text will not be editable', 'Perfect for PDFs with visual content and charts'],
    relatedSlugs: ['ppt-to-pdf', 'pdf-to-word', 'pdf-to-jpg'],
  },
  'ppt-to-pdf': {
    slug: 'ppt-to-pdf',
    label: 'PowerPoint to PDF',
    tagline: 'Seal your slides in PDF armor',
    description: 'Convert PPT and PPTX presentations to universally viewable PDFs. Protect your design — share without fear of font or layout shifts.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Nodachi',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/ppt-to-pdf',
    acceptedTypes: ['application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    acceptedLabel: 'PPT or PPTX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Animations and transitions will not be preserved', 'All embedded images and fonts are captured', 'Processing takes 15-45 seconds depending on file size'],
    relatedSlugs: ['pdf-to-ppt', 'compress', 'word-to-pdf'],
  },
  'pdf-to-excel': {
    slug: 'pdf-to-excel',
    label: 'PDF to Excel',
    tagline: 'Extract data like extracting secrets',
    description: 'Pull tables and data from PDFs directly into Excel spreadsheets. A ninja always knows how to retrieve what is hidden.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇒',
    ninjaWeapon: 'Tekko',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/pdf-to-excel',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    outputExt: 'xlsx',
    tips: ['Best results on PDFs with clear table borders', 'Free-form layouts may require manual cleanup', 'Run OCR first on scanned PDFs before converting'],
    relatedSlugs: ['excel-to-pdf', 'pdf-to-word', 'ocr'],
  },
  'excel-to-pdf': {
    slug: 'excel-to-pdf',
    label: 'Excel to PDF',
    tagline: 'Forge spreadsheets into PDFs',
    description: 'Transform XLSX and XLS spreadsheets into clean, shareable PDFs. Every cell, formula result, and chart — preserved in PDF armor.',
    category: 'Convert',
    type: 'heavy',
    icon: '⇐',
    ninjaWeapon: 'Naginata',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/jobs/excel-to-pdf',
    acceptedTypes: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    acceptedLabel: 'XLS or XLSX files',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Each worksheet becomes a separate PDF page', 'Print area settings are respected', 'Freeze panes and row/column headers are captured'],
    relatedSlugs: ['pdf-to-excel', 'compress', 'word-to-pdf'],
  },
  'pdf-to-jpg': {
    slug: 'pdf-to-jpg',
    label: 'PDF to JPG',
    tagline: 'See every page as an image',
    description: 'Convert each PDF page into a high-resolution JPG image. Extract charts, diagrams, or visuals — or create a full image archive.',
    category: 'Convert',
    type: 'easy',
    icon: '⊡',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_convert.png',
    apiPath: '/v1/tools/pdf-to-jpg',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'dpi', label: 'Resolution (DPI)', type: 'select', options: ['72', '150', '300'], defaultValue: '150' },
    ],
    outputExt: 'zip',
    tips: ['150 DPI is recommended for web use', '300 DPI produces print-quality images', 'Multiple pages are delivered as a ZIP archive'],
    relatedSlugs: ['jpg-to-pdf', 'compress', 'split'],
  },
  'jpg-to-pdf': {
    slug: 'jpg-to-pdf',
    label: 'JPG to PDF',
    tagline: 'Bind images into one scroll',
    description: 'Convert single or multiple JPG images into a PDF. Adjust orientation and margins — create a perfect multi-page image document.',
    category: 'Convert',
    type: 'easy',
    icon: '⊟',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/jpg-to-pdf',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/bmp'],
    acceptedLabel: 'JPG, PNG, BMP images',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload multiple images to create a multi-page PDF', 'Images are arranged in upload order', 'PNG and BMP images are also supported'],
    relatedSlugs: ['pdf-to-jpg', 'merge', 'compress'],
  },
  'html-to-pdf': {
    slug: 'html-to-pdf',
    label: 'HTML to PDF',
    tagline: 'Capture webpages with precision',
    description: 'Convert any webpage or HTML content to PDF. Paste a URL or raw HTML — we render it with full CSS support and save it to PDF.',
    category: 'Convert',
    type: 'easy',
    icon: '⊙',
    ninjaWeapon: 'Grappling Hook',
    ninjaImage: '/ninja_hero.png',
    apiPath: '/v1/tools/html-to-pdf',
    acceptedTypes: ['text/html'],
    acceptedLabel: 'HTML files or URL',
    multiFile: false,
    outputExt: 'pdf',
    tips: ['Enter a URL to convert any webpage', 'Or paste raw HTML for direct conversion', 'Best for documentation pages, reports, and articles'],
    relatedSlugs: ['jpg-to-pdf', 'compress', 'word-to-pdf'],
  },
  watermark: {
    slug: 'watermark',
    label: 'Watermark PDF',
    tagline: 'Brand every page with your mark',
    description: 'Stamp text or an image watermark on your PDF. Control opacity, position, and typography — mark your document as yours.',
    category: 'Edit',
    type: 'easy',
    icon: '◎',
    ninjaWeapon: 'Ink Brush',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/watermark',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'text', label: 'Watermark Text', type: 'text', placeholder: 'e.g. CONFIDENTIAL' },
      { key: 'opacity', label: 'Opacity (0.1 - 1.0)', type: 'number', defaultValue: 0.3, min: 0.1, max: 1 },
    ],
    outputExt: 'pdf',
    tips: ['Use CONFIDENTIAL, DRAFT, or your company name', 'Lower opacity (0.1-0.3) gives a subtle watermark', 'The watermark appears on every page'],
    relatedSlugs: ['protect', 'rotate', 'page-numbers'],
  },
  rotate: {
    slug: 'rotate',
    label: 'Rotate PDF',
    tagline: 'Find the right angle',
    description: 'Rotate pages 90°, 180° or 270° — all pages or a specific selection. A ninja adjusts to every angle to find the perfect strike.',
    category: 'Edit',
    type: 'easy',
    icon: '↻',
    ninjaWeapon: 'Shuriken',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/rotate',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'angle', label: 'Rotation Angle', type: 'select', options: ['90', '180', '270'], defaultValue: '90' },
      { key: 'pages', label: 'Apply to Pages', type: 'text', placeholder: 'all (or 1,3,5)', defaultValue: 'all' },
    ],
    outputExt: 'pdf',
    tips: ['Enter "all" to rotate every page', 'Specify page numbers like "1,3,5" for selective rotation', '90° clockwise is the most common rotation'],
    relatedSlugs: ['organize', 'crop', 'merge'],
  },
  crop: {
    slug: 'crop',
    label: 'Crop PDF',
    tagline: 'Remove the unnecessary',
    description: 'Trim margins or select specific content areas. Apply cropping to individual pages or the entire document — like cutting away the excess.',
    category: 'Edit',
    type: 'easy',
    icon: '⊡',
    ninjaWeapon: 'Chakram',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/crop',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'left', label: 'Left margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'bottom', label: 'Bottom margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'right', label: 'Right margin (pts)', type: 'number', defaultValue: 0, min: 0 },
      { key: 'top', label: 'Top margin (pts)', type: 'number', defaultValue: 0, min: 0 },
    ],
    outputExt: 'pdf',
    tips: ['Margins are measured in PDF points (1pt = 1/72 inch)', '72 points = 1 inch of margin removed', 'Start with small values and adjust as needed'],
    relatedSlugs: ['rotate', 'organize', 'split'],
  },
  'page-numbers': {
    slug: 'page-numbers',
    label: 'Page Numbers',
    tagline: 'Number your pages with honor',
    description: 'Add professional page numbers to your PDF. Choose position, font size, and starting number — applied with precision to every page.',
    category: 'Edit',
    type: 'easy',
    icon: '⊕',
    ninjaWeapon: 'Ink Brush',
    ninjaImage: '/ninja_tools.png',
    apiPath: '/v1/tools/page-numbers',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'position', label: 'Position', type: 'select', options: ['bottom-center', 'bottom-right', 'bottom-left', 'top-center', 'top-right', 'top-left'], defaultValue: 'bottom-center' },
      { key: 'start', label: 'Start Number', type: 'number', defaultValue: 1, min: 1 },
      { key: 'font_size', label: 'Font Size', type: 'number', defaultValue: 12, min: 8, max: 24 },
    ],
    outputExt: 'pdf',
    tips: ['Bottom-center is the most professional placement', 'Use "Start Number" to continue numbering from a previous document', 'Font size 10-12 is ideal for most documents'],
    relatedSlugs: ['watermark', 'organize', 'merge'],
  },
  protect: {
    slug: 'protect',
    label: 'Protect PDF',
    tagline: 'Shield your secrets',
    description: 'Encrypt your PDF with a password. Unauthorized access is forbidden — only those with the password can open the document.',
    category: 'Security',
    type: 'easy',
    icon: '🔒',
    ninjaWeapon: 'Iron Shield',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/protect',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'password', label: 'Password', type: 'text', placeholder: 'Enter a strong password' },
    ],
    outputExt: 'pdf',
    tips: ['Use a strong password with mixed characters', 'Store your password safely — we cannot recover it', 'AES-128 encryption is applied by default'],
    relatedSlugs: ['unlock', 'watermark', 'pdf-to-pdfa'],
  },
  unlock: {
    slug: 'unlock',
    label: 'Unlock PDF',
    tagline: 'Break the chains',
    description: 'Remove password protection from your PDF. Gain the freedom to edit, print, and share — like a ninja escaping any trap.',
    category: 'Security',
    type: 'easy',
    icon: '🔓',
    ninjaWeapon: 'Lock Pick',
    ninjaImage: '/ninja_security.png',
    apiPath: '/v1/tools/unlock',
    acceptedTypes: ['application/pdf'],
    acceptedLabel: 'PDF files only',
    multiFile: false,
    options: [
      { key: 'password', label: 'Current Password', type: 'text', placeholder: 'Enter the PDF password' },
    ],
    outputExt: 'pdf',
    tips: ['You must know the password to unlock the file', 'The resulting PDF will have no password restriction', 'We do not store passwords after processing'],
    relatedSlugs: ['protect', 'repair', 'compress'],
  },
  'scan-to-pdf': {
    slug: 'scan-to-pdf',
    label: 'Scan to PDF',
    tagline: 'Mobile capture → perfect PDF',
    description: 'Upload photos taken from your phone or scanner. We\'ll convert them into a clean, multi-page PDF document instantly.',
    category: 'Security',
    type: 'heavy',
    icon: '📷',
    ninjaWeapon: 'Spy Lens',
    ninjaImage: '/ninja_ocr.png',
    apiPath: '/v1/jobs/scan-to-pdf',
    acceptedTypes: ['image/jpeg', 'image/png', 'image/tiff', 'image/bmp'],
    acceptedLabel: 'JPG, PNG, TIFF images',
    multiFile: true,
    outputExt: 'pdf',
    tips: ['Upload multiple scan images to merge into one PDF', 'Ensure good lighting for best OCR results', 'TIFF format is supported for high-resolution scans'],
    relatedSlugs: ['ocr', 'jpg-to-pdf', 'compress'],
  },
  ocr: {
    slug: 'ocr',
    label: 'OCR PDF',
    tagline: 'Read the unreadable',
    description: 'Extract text from scanned PDFs and images using AWS Textract AI. Turn a photo of a document into searchable, selectable text.',
    category: 'Security',
    type: 'ocr',
    icon: '👁',
    ninjaWeapon: 'Cybernetic Eye',
    ninjaImage: '/ninja_ocr.png',
    apiPath: '/v1/ocr',
    acceptedTypes: ['application/pdf', 'image/jpeg', 'image/png', 'image/tiff'],
    acceptedLabel: 'PDF, JPG, PNG or TIFF',
    multiFile: false,
    outputExt: 'txt',
    tips: ['Supports 9 languages including English, Japanese, and more', 'PDFs under 5MB are processed synchronously (faster)', 'Larger PDFs use async Textract (may take up to 90 seconds)'],
    relatedSlugs: ['scan-to-pdf', 'pdf-to-word', 'compress'],
  },
};

export const TOOL_LIST = Object.values(TOOLS);

export function getRelatedTools(slug: string): ToolConfig[] {
  const tool = TOOLS[slug];
  if (!tool) return [];
  return tool.relatedSlugs.map(s => TOOLS[s]).filter(Boolean);
}

export function getToolsByCategory(category: ToolCategory): ToolConfig[] {
  return TOOL_LIST.filter(t => t.category === category);
}

export const CATEGORY_META: Record<ToolCategory, { label: string; desc: string; icon: string }> = {
  Organize: { label: 'Organize PDF', desc: 'Arrange and restructure your documents', icon: '⊞' },
  Optimize: { label: 'Optimize PDF', desc: 'Compress, repair, and archive your files', icon: '↘' },
  Convert:  { label: 'Convert PDF',  desc: 'Transform between file formats at ninja speed', icon: '⇒' },
  Edit:     { label: 'Edit PDF',     desc: 'Modify and customize your PDF content', icon: '✎' },
  Security: { label: 'PDF Security', desc: 'Protect, unlock, and extract from PDFs', icon: '🔒' },
};
